ERROR - 2022-05-27 11:29:38 --> Error connecting to the database: Unknown database 'almexterno'
CRITICAL - 2022-05-27 11:29:38 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'almexterno'
#0 C:\xampp\htdocs\almexterno\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\almexterno\app\Models\UsuarioModel.php(44): CodeIgniter\Database\BaseConnection->query('select usu.idus...')
#2 C:\xampp\htdocs\almexterno\app\Views\template\layout.php(12): App\Models\UsuarioModel->getUsuario('1')
#3 C:\xampp\htdocs\almexterno\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\almexterno\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\almexterno\system\Common.php(1250): CodeIgniter\View\View->render('template/layout', Array, true)
#6 C:\xampp\htdocs\almexterno\app\Controllers\Producto.php(165): view('template/layout', Array)
#7 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(948): App\Controllers\Producto->productos()
#8 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(444): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Producto))
#9 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(344): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\almexterno\index.php(36): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-05-27 11:29:38 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\almexterno\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\almexterno\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Producto), true)
#2 C:\xampp\htdocs\almexterno\system\Debug\Exceptions.php(278): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\almexterno\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
